#pragma once

// description of errors that may occur
#define NO_ERRORS 0
#define INCORRECT_ARGUMENTS_PASSED_TO_FUNCTION 1
#define MEMORY_ALLOCATION_ERROR 44
#define FILE_OPENING_ERROR 15
#define TESTS_FAILED_ERROR -1
#define ERROR_INCORRECT_EXPRESSION_IN_FILE 11