#pragma once
#define NO_ERRORS 0
#define MEMORY_ALLOCATION_ERROR 44
#define INCORRECT_ARGUMENTS_PASSED_TO_FUNCTION 1
#define FILE_OPENING_ERROR 15
#define TESTS_FAILED_ERROR (-1)
#define INVARIANT_VIOLATION 111